apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "6IrqqiVflm/o8VJBAzYEUZ/Cn5/JPNtn+GhzO9PVyApCyzGNngp8UqVdI/WIW+uS\r\nkJHg82tn7nt54Byx83CdNLG93i8BmSjIiySPCQ5Z3xYBGXHcDci11MZOt208k4Gc\r\nE1kF2pFbD2sQ8Wlj8pz2JZPIWSs9pI15rUdkWJWzdVg="
