apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "K+y9UrHkEfvD0DihNgE+lYrlocF0ZPQuosjv5Nrb8lb65rl+jTcvUndRpllR5GcB\r\ng3Gf22DjmoUWIoAwQ5XW/dJrRzuImzmX0plPbjq7xscwIIeohOZjbEQGKMif1Zai\r\n8coI9w5LF48M4/3KHAS8hQF/m4Ni+8n5Qq/SnoeDFVg="
