apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "ea3xZOYtqDcX32jVi+zv71NTa1gCmekSFDIjdDK68qJsQtBKbiROm/XezpUN4JQk\r\nkZ3+WUx+xQEY86zcNnlLdMP15gAUf43TZZtPkpewjzMFBGQ60n+AKPQOAKx71ljV\r\ngUrZvVwCbwInAChuvn57Yjw46+kWHpvU5JORLlX8zhU="
