apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "ACpKOxK1D9BxzzQqrvh/rQcp2XzNXHlEvRPmUqII/pW7PwZhbkqwLwers89AV8CQ\r\nQ+bwYZQP8TVZ/KeuVbePRZmPj9vjCiNT1/EqCgqvxl0dDCFCb1i7/P1QXa806fU0\r\nICmboECcvbgr5kaecgv7pMp/1yqu1zL4xSrXp8jdAuI="
