apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "x+UyiIbAjMxrNaQaq+HwEgppCiwh/pt9sMINkuKqWug0MifB/qPewf7p4kFMT6Y0\r\nt6ho+BxgqvzsRlsEyD5vDUL6UaYyM3xmOh+nG5NUGO+trmBGFl+NMjKU3wS5dqLf\r\nKFPBTBZ/1a+IRX6UCik/3Q7axrIrjSbH7jfjrqtmEBg="
