apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "0RYbjSbmrbr1DpKZJsjgZhigMqpr6swvBdC6Qgy3asmlM3bomIgxDuvKLxyNFJ+5\r\njUgvkE6XkIjg6KdMthh/M8Rb1IHhHsoDR7tGx6bhFZ1dGXyn8BpKSQhMgu6cV8+c\r\nyupDouPoUx92TV58Il1eSJVfZDVP6hEDEKl5rR5Xbyc="
