apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "/MiRace5PWgvaFkCOqJtVdZtPFHHfVgzq4CtCc7N6rnZouth+hyn5pufT+rml4wi\r\n/pbNGArHUsIx+nD0Ra+C4YR0Kw2xAItB6ND+XcULfiiysb616XG/ikmG2zIZ5IJe\r\nafMxaK8Vfe3EjUw/aebWhhdS5IOix0EFb4Guaid//D0="
