apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "wmFWdId48RFkFGJ94HGdW8/7F56XLrsrLzGHFykSsDe6kD1M8bFio8AtwhvgOBqk\r\ncOr1YtondIKv9WPYl/SdJq2Ao2psZShWC0Bz01QNxliMiaXQDHNsMtPpRpAxgT7C\r\nFwHgh+v0mMU2gm2QjlX82ai//liBs00iTRa1DLBfVIA="
