apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "88yWcLOzrSp9LL6l1GOkaZsjghU6vRkNPC88wtopbc2XDmhtw8JboC9dYWEzlGzO\r\nfBcAkv4etLxfRha5Lxws0mlQsT78swLJLdxKHBf4QNTIlleO27SX9bdngWLcBLEu\r\nye20vtXEIyeEmHwrlT6EjmXUE4+ZTAq9+F5QFJ+EBFA="
