apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "hAJRa08JWf43Dg+arnDYch13mUjYuKct6kkeF3QVwUhvCrIFT+NypiOTVS69ACkY\r\nsIJ8e+e5GrPeicpVLSV380HdASvmIOMWS3doKLaU2I19ZHiKLyDgwgOluQXVdpFa\r\nuId6P4XWFX8NmALTMnYXSjJbXI535361QTn/8suc77Y="
