apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "gLWG6jFYM/kTI517zrn11OSPIbo4Z31cnsSVPEiMPCa6wHRjfap/n6bSuyvaabhI\r\n+/0kcBbGl+2ahk9WD2ggiW8e6xzlcnHx5naOXgvIWUBCTuqIYg64D0sRC1QO8xyj\r\nN5FbX/T2uoaAWMWi0Oc/yubDGW2ujQp/E+gKzQE9+44="
