apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "ZxPozYDOufibxEcObEKg3+adtednr8hfayw2Lf9a/EEwMRVAZq0J6aZWcoa2vxlw\r\napC+RGD6rxbMONEhLJSKC6aExLwY3HrOse+mIc5OcMOH5pAgcdac1uMAdsgnFmdb\r\nLFsHv+XFdAUeVXqykmascOChSKA2Wjv9FsHsJs8V6qU="
