apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "fVaoBYFuvwVtJqd/+d5zHrpMCGEWinOdOnhFyG/KhkE4l5sP9Fh77fQk7Kodq9SD\r\n1iUAu3du38T/2xhUlCIXvUTFqq2fNggwNpi4ZG5NqomrD537DjXzl7CSputF87Be\r\nZhVVvqBM6GAQMM4HqCAgvxRS0bchO0r5V62CzEk9XS4="
