apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "TYBN+/D+8k0Ou+nak66mpuCIfv8lDlcMnXFa1ksYCDBF3CmXtMtV9AflKmcreJOk\r\nTxGKNycToYVw709DyhBXtF4+COWOB4vnmbFxtKvY9Rs8KpJ8dveWGeoZDyTZBgmw\r\nfq2GXUG83nxVjp6qWZ7ZKULzH5qZDyFZYq1TWH3eDk8="
