apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "4AlzFAguSXgB7rdfg/AN4KF44PvZQfBlPZBHU0R2W/f68YFMEVCsnsWpLVhyeuoR\r\nrPLbzmpYrOsWWabGzPzExGR5ZO+0GEjGB1sr/Oz5UZ7W/+yvd8EoT/nqo6ksOz1u\r\nrJTYIr1MwvloLLh3Lt45/+mxjn06Ydcqu9EPIHB4vFk="
